[phases.setup]
nixPkgs = ["python311"]

[build]
command = "python -m pip install --upgrade pip && pip install -r requirements.txt"

[start]
command = "gunicorn --bind :$PORT --workers 1 --threads 8 --timeout 0 app:app"
